== Modelltransformationen
=== Transformation vom Bearbeitungsmodell ins Publikationsmodell
* Quellmodell: https://raw.githubusercontent.com/ch-sz-geo/A064/refs/heads/main/models/SZ_Schutzwald_V1_Bearbeitung.ili[Bearbeitungsmodell "SZ_Schutzwald_V1" (Version: 2025-01-23)]
* Zielmodell: https://raw.githubusercontent.com/ch-sz-geo/A064/refs/heads/main/models/SZ_Schutzwald_V1.ili[Publikationsmodell verwaltungsintern "SZ_Schutzwald_V1_Bearbeitung" (Version: 2025-01-23)]

=== Transformation ins minimale Geodatenmodell des Bundes
* Quellmodell: Das hier beschriebene Datenmodell
* Zielmodell: http://models.geo.admin.ch/BAFU/todo[<Modellname> (Version: 2023-03-20)]

=== Transformation ins Transfermodell ÖREB-Kataster
* Quellmodell: Das hier beschriebene Datenmodell
* Zielmodell: https://models.geo.admin.ch/V_D/OeREB/OeREBKRMtrsfr_V2_0.ili[OeREBKRMtrsfr_V2_0 (Version: 2021-04-14)]

==== Klasse `+DarstellungsDienst+`
[cols=2*,options="header"]
|===
| Quellattribut | Zielattribut
| `+ch.sz.a094b.oereb.wald.statische_waldgrenze.linie+`
| `+VerweisWMS+`
|===

==== Klasse `+Eigentumsbeschraenkung+`
[cols=2*,options="header"]
|===
| Quellattribut | Zielattribut
| Der Wert für `+Rechtsstatus+` wird regelbasiert abgeleitet (siehe unten) | `+Rechtsstatus+`
| Datum, an dem die Publikation im ÖREB-Katastersystem erfolgt; wird durch den Publikationsprozess gesetzt m| publiziertAb
| (aktuell nicht verwendet und daher leer) m| publiziertBis
|===

Regeln für die Ableitung des Wertes für `+Rechtsstatus+`:
|===
h| Regel h| Rechtsstatus
a| Der Wert von `+Waldgrenze.Begruendungsverfahren+` muss gesetzt sein und der Wert von `+Waldgrenze.Aufhebungsverfahren+` muss leer sein. +
Zudem darf der Code des Waldfeststellungstatus `+Verfahrensstatus.Code+` (hergeleitet über `+Waldfeststellung.rVerfahrensstatus+`) nicht einer der folgenden Werte aufweisen: 'abgeschlossen', 'abgeschlossen_ohne_Verfuegung', 'unbekannt'.
| `+laufendeAenderung_Begruendung+`
| Der Wert von `+Waldgrenze.Begruendungsverfahren+` muss gesetzt sein und der Wert von `+Waldgrenze.Aufhebungsverfahren+` muss leer sein. +
Zudem muss der Code des Waldfeststellungstatus `+Verfahrensstatus.Code+` (hergeleitet über `+Waldfeststellung.rVerfahrensstatus+`) den Wert 'abgeschlossen' aufweisen. | `+inKraft+`
| Die Werte von `+Waldgrenze.Begruendungsverfahren+` und `+Waldgrenze.Aufhebungsverfahren+` müssen gesetzt sein. +
Zudem darf der Code des Waldfeststellungstatus `+Verfahrensstatus.Code+` des Aufhebungsverfahrens (hergeleitet über `+Waldfeststellung.rVerfahrensstatus+`) nicht einer der folgenden Werte aufweisen: 'abgeschlossen', 'abgeschlossen_ohne_Verfuegung', 'unbekannt'.
| `+laufendeAenderung_Aufhebung+`
| Die Werte von `+Waldgrenze.Begruendungsverfahren+` und `+Waldgrenze.Aufhebungsverfahren+` müssen gesetzt sein. +
Zudem muss der Code des Waldfeststellungstatus `+Verfahrensstatus.Code+` des Aufhebungsverfahrens (hergeleitet über `+Waldfeststellung.rVerfahrensstatus+`) den Wert 'abgeschlossen' aufweisen.
| `+inKraft_Aufhebung+`
|===

==== Klasse `+Geometrie+`
[cols=2*,options="header"]
|===
| Quellattribut | Zielattribut
| - - - m| Punkt
m| Waldgrenze.Geometrie m| Linie
| - - - m| Flaeche
| analog `+Eigentumsbeschraenkung.Rechtsstatus+` m| Rechtsstatus
| analog `+Eigentumsbeschraenkung.publiziertAb+` m| publiziertAb
| analog `+Eigentumsbeschraenkung.publiziertBis+` m| publiziertBis
| https://www.geocat.ch/geonetwork/srv/ger/catalog.search#/metadata/8646c41b-543e-401f-836d-4b6beca7370d[Link auf GeoCat] m| MetadatenGeobasisdaten
|===

==== Klasse `+LegendeEintrag+`
[cols=2*,options="header"]
|===
| Quellattribut | Zielattribut
m| Typ.Symbol m| Symbol
m| Typ.Name m| LegendeText
m| Typ.Code m| ArtCode
m| https://data.geo.sz.ch/public/Themen/A057b/[Legende.xml] m| ArtCodeliste
| fix: " `+ch.StatischeWaldgrenzen+` " m| Thema
| - - - m| SubThema
|===

=== Transformation ins WebGIS
* Quellmodell: Das hier beschriebene Datenmodell
* Zielmodell: keines (siehe unten)

==== Allgemeines
Für die WebGIS-Publikation werden die Daten optimiert. Dies ist häufig mit einer Denormalisierung verbunden ("flachwalzen" der Daten). Der Attributumfang richtet sich nach den Anforderungen der zuständigen Stelle und ist im Normalfall geringer als im Ausgangsmodell. Eine weitere Besonderheit kommt den Tabellen der WebGIS-Datenbank zu. Sie weisen Standard-Spalten auf, welche nicht Teil des Datenmodells sind. Es handelt sich um folgende Spalten:

**Standardspalten:**
[cols=2*,options="header"]
|===
| Spaltenname | Beschreibung
m| id | eindeutige Identifikation des Objektes; kann von der OID der Ausgangsdaten abweichen, falls Objekte zum Zweck der Publikation aufgeteilt werden müssen
m| etl_dt | Zeitstempel, an dem der Datensatz in die Tabelle geschrieben wurde (etl: extract - transfer - load)
m| etl_job | Name des Jobs, mit dem die Daten auf die Tabelle geschrieben wurde
m| asof_dt | Datum, an dem am Datensatz die letzten Änderungen vorgenommen wurden. Dieser Wert wird in den Metadaten des Datensatzes nachgeführt.
|===

Das WebGIS bezieht die Daten direkt aus der Datenbank. Aus diesem Grund wird nachfolgend von "Tabelle" und "Spalte" anstelle von "Klasse" und "Attribut" gesprochen. Der Klassenname erscheint lediglich in der Überschrift.

==== Tabelle der `+Waldgrenze+`
[cols=2*,options="header"]
|===
| Quellattribut | Zielspalte
| - - - | (Standardspalten gemäss den Angaben oben)
| `+Typ.Code+` +
hergeleitet über `+Waldgrenze.rTyp+` m| typ
| `+Typ.Name+` +
hergeleitet über `+Waldgrenze.rTyp+` m| bezeichnung
m| Waldgrenze.Geometrie m| geom
|===

==== Tabelle der `+Stockgrenze+`
[cols=2*,options="header"]
|===
| Quellattribut | Zielspalte
| - - - | (Standardspalten gemäss den Angaben oben)
| `+Verfahren.Verfuegungsnummer+` +
hergeleitet über: +
`+Stockgrenze.rWaldgrenze+` &#x2192; +
`+Waldgrenze.Begruendungsverfahren+`
m| verfuegung_datum_nr
m| Stockgrenze.Geometrie m| geom
|===

[cols="e,m,^,>s",width="25%"]
|===
|1 >s|2 |3 |4
^|5 2.2+^.^|6 .3+<.>m|7
^|8
|9 2+>|10
|===


ifdef::backend-pdf[]
<<<
endif::[]
